export {
  BROWSER_CACHE_HEADER,
  BROWSER_NO_STORE_HEADER,
  CDN_CACHE_HEADER,
  CDN_NO_STORE_HEADER,
  MEMORY_CACHE_MAX_KEYS,
  MEMORY_CACHE_MAX_BYTES,
  L1_MAX_TTL_MS,
} from "@/server/config/upstream";
